; PROGRAM TO RENDER A X + Y GRADIENT

    LUI R0, 0x20    ; REGISTER TO STORE FRAMEBUFFER STARTING ADDRESS
    LLI R1, 1       ; REGISTER TO STORE 1
    XOR R2, R2, R2  ; REGISTER TO STORE CURRENT ADDRESS
    XOR R3, R3, R3  ; REGISTER TO STORE THE X COORDINATE
    XOR R4, R4, R4  ; REGISTER TO STORE THE Y COORDINATE
    LUI R5, 0x80    ; REGISTER TO STORE FINAL ADDRESS

loop:
    SHR R3, R2, 8   ; GET X COORDINATE
    ADD R3, R3, R3  ; SCALE X BY 2 AS HE ONLY GOES UP TO 128
    LDI R6, 0xFF
    AND R4, R2, R6  ; GET Y COORDINATE
    ADD R6, R3, R4  ; CALCULATE X + Y
    ADD R7, R2, R0  ; GET REAL CURRENT ADDRESS
    MOV [R7], R6    ; PUT X + Y ON FRAMEBUFFER
    ADD R2, R2, R1  ; INCREMENT CURRENT ADDRESS
    CMP R2, R5      ; COMPARE CURRENT AND FINAL ADDRESS
    LDI R6, end
    JEQ R6          ; END THE PROGRAM IF THEY ARE EQUAL
    LDI R6, loop
    JMP R6

end:
    LDI R6, end
    JMP R6