; THIS SHOULD SHOW A RED STRIP ON TOP AND A GREEN STRIP ON THE BOTTOM

.dw COLORS 0xf800 0x07e0

    LUI R0, 0x20    ; REGISTER TO STORE FRAMEBUFFER STARTING ADDRESS
    LLI R1, 1       ; REGISTER TO STORE 1
    XOR R2, R2, R2  ; REGISTER TO STORE CURRENT ADDRESS
    LUI R4, 0x80    ; REGISTER TO STORE FINAL ADDRESS
    LDI R5, COLORS  ; REGISTER TO STORE ADDRESS OF CURRENT COLOR

loop:
    LDI R6, 0x4000
    CMP R2, R6      ; IF X COORDINATE IS 64, CHANGE COLOR
    LDI R6, else_label
    JNE R6
    ADD R5, R5, R1  ; IF CURRENT ADDRESS IS 0X4000, CHANGE COLOR, ELSE, CONTINUE THE LOOP
else_label:
    ADD R6, R0, R2  ; GET THE REAL CURRENT ADDRESS
    MOV [R6], [R5]
    ADD R2, R2, R1  ; INCREMENT CURRENT ADDRESS
    CMP R2, R4      ; COMPARE CURRENT AND FINAL ADDRESS
    LDI R6, loop
    JNE R6          ; IF THEY ARE NOT EQUAL, KEEP LOOPING, OTHERWISE END THE PROGRAM

end:
    LDI R6, end
    JMP R6
